name: .NET Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore solution
      run: dotnet restore OrderMicroservices.sln

    - name: Build solution
      run: dotnet build OrderMicroservices.sln --configuration Release --no-restore